### ISSUE TITLE
can't mount volume - invalid name

### ISSUE THREAD

**Issue by msbarrios** [bwalex/tc-play#69]
This is my first time trying tcplay. I couldn't mount my encrypted volume created with truecrypt. This volume was created 5 years ago (or more). I followed the basic instructions in the wiki. The error message that I get gives me no clues of what's the problem. See below:

 # losetup /dev/loop0 myfile.tc
 # tcplay --map=myfile.tc --device=/dev/loop0
 Passphrase:
 Name "myfile.tc.0" invalid. It contains "/".
 dm_task_set_name failed
 Could not set up mapping myfile.tc

Is there any option in tcplay that I should be using?

**Comment by mhogomchungu** [comment]
hi,not tcplay developer,just saw your bug and decided to comment on it.

tcplay only supports TrueCrypt volumes that use xts mode and this means volumes that were created with version 5.0 of TrueCrypt going up(this version was released february of 2008).

The command you entered is correct and i suspect tcplay is failing to open your volume because it uses older modes of operations tcplay does not recognize.

try cryptsetup[1] since it supports more TrueCrypt modes of operations and it may support your volume.You will need atleast version 1.6.0 of cryptsetup to be able to unlock TrueCrypt volumes.

[1] https://gitlab.com/cryptsetup/cryptsetup/blob/master/README.md

**Comment by bwalex** [comment]
This actually sounds to me like you had a literal slash in your map target, or mixed up the device and the map target.
