### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by q2dg** [bwalex/tc-play#73]
Last commit was from 2014...
Maybe it's time to use Veracrypt as an alternative...

**Comment by bwalex** [comment]
I'd call it mature rather than abandoned. It does what it says on the tin of allowing TrueCrypt volume access via dm. I should have probably handled #65 better, but to be fair, I'm not terribly keen on the whole host of arbitrary forks of TrueCrypt, such as VeraCrypt (after all, at least at the time, the only difference in implementation was a bump of iteration count, with a range of other incompatibilities). In other words - not sure why I'd be adding VeraCrypt support rather than one of the other arbitrary forks.

However, if anyone wants to submit something that just generally supports all of these arbitrary forks like VeraCrypt that just tweak an iteration count here or there, I'd be all ears.

**Comment by mhogomchungu** [comment]
I have a fork here[1] that adds support for VeraCrypt volume and VeraCrypt volumes that uses a PIM value.

For example, a command that creates a VeraCrypt volume that uses a PIM value of "1" in "/dev/loop0" is:

```
zuluplay -c -d /dev/loop0 --veracrypt-mode  --pim 1
```

[1]https://github.com/mhogomchungu/zuluplay

**Comment by PsySc0rpi0n** [comment]
@bwalex but are you still working on this project and maintaining it?

**Comment by bwalex** [comment]
@PsySc0rpi0n I can't say I'm actively working on it, but as I stated almost 2 years ago, I'd be happy to take e.g. a pull request that adds generic support for all the TrueCrypt forks that have come up since (instead of some very specific VeraCrypt-only change) - e.g. reading some mapping of name to parameter values.

**Comment by bwalex** [comment]
VeraCrypt support has been merged.
